5.4.1 不带参数的层

In [4]:
import torch
from torch import nn
import torch.nn.functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return x - x.mean()

In [5]:
layer  = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())


In [6]:
y = net(torch.rand(4,8))
y.mean()

tensor(-1.8626e-09, grad_fn=<MeanBackward0>)

5.4.2 带参数的层

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, outs):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(in_units, outs))
        self.bias = nn.Parameter(torch.zeros(outs, ))

    def forward(self, x):
        linear = torch.mm(x, self.weight.data) + self.bias.data
        return F.relu(linear)


In [10]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[0.7370, 0.4187, 0.6029],
        [0.9375, 0.1997, 0.5070],
        [0.7954, 0.8039, 0.0442],
        [0.6217, 0.2986, 0.4828],
        [0.1335, 0.5931, 0.6079]], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[2.2985, 1.2444, 1.2532],
        [2.0172, 1.1306, 0.8783]])

In [13]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net((torch.rand(2, 64)))

tensor([[80.7263],
        [66.0047]])