### 2.2.1 入门

In [65]:
import torch

In [66]:
# 生成一个全是0的张量
x = torch.arange(12 )

In [67]:
# 查看张量的形状
x.shape

torch.Size([12])

In [68]:
# 查看张量的元素总数
x.numel()

12

In [69]:
# 改变张量的形状
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [70]:
# 生成一个全是0的张量
torch.zeros((2,3,4))    


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [71]:
# 生成一个全是1的张量
torch.ones((2,3,4)) 

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [72]:
# 生成一个随机张量，张量中的元素服从均值为0，标准差为1的正态分布
torch.randn(3,4)

tensor([[-0.2803,  0.4538, -0.6796, -0.8183],
        [ 0.2491, -0.5988,  1.4421,  0.6577],
        [-0.5208, -0.6032,  0.7482, -1.1787]])

In [73]:
# 列表转张量
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 运算符

In [74]:
# + - * / ** 运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [75]:
# 指数运算
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [76]:
# 拼接张量
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [77]:
# 构建二元张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [78]:
#   求和
X[1][:].sum()
print(X[1][:])
print(X[:][1])

tensor([4., 5., 6., 7.])
tensor([4., 5., 6., 7.])


### 2.1.3 广播机制

### 2.1.4 索引和切片

### 2.1.5 节省内存
利用 id(x) ,类似指针，但不相同

In [79]:
before = id(Y)
Y = Y + X
id(Y) == before

False

此时 `Y` 的 id 发生变化,说明 `Y`指向了 新的内存空间，会消耗跟多的内存， 还有可能让其他程序的  `Y` 变成错误的指向。

In [80]:
z = torch.zeros_like(Y)
print('id(z):', id(z))  # id()函数返回内存地址
z[:] = X + Y
print('id(z):', id(z))

id(z): 137899034446720
id(z): 137899034446720


这样用z可以避免错误指向。
或者 原地计算。

In [81]:
# 通过 x+=y,x[:] = x+y来减少操作的内存开销
before = id(X)
x+=y
id(X)==before

True

此时 `X` id 没有发生改变。
### 2.1.6 转换为其他pyton对象

In [82]:
import numpy

In [83]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

大小为1的张量可以转换为python标量

In [84]:
a = torch.tensor([3.5]) 
a,a.item(),float(a),int(a)      # item()将张量中的元素以标量的形式返回

(tensor([3.5000]), 3.5, 3.5, 3)