2.2.1读取数据集

In [2]:
import os

In [9]:
os.makedirs(os.path.join('..', 'data') , exist_ok=True)
fil = os.path.join("..", 'data', 'hourse_tiny.csv')

# 注意 第二列 NA 前面后面都没有空格
with open(fil, 'w') as f:
    f.write('NumRooms, Alley, Price\n')
    f.write('NA, Pave, 127500\n')
    f.write('2,NA, 106000\n')
    f.write('4,NA, 178100\n')
    f.write('NA,NA, 140000\n')

In [10]:
import pandas as pd


In [11]:
data = pd.read_csv(fil , na_values=['NA'])
print(data)


   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


2.2.2 处理缺失值

-1- 用均值填充

-2- 单独作为一个类别

In [25]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
# 注意新版本 mean() 不会忽略字符串
inputs = inputs.fillna(inputs.mean(numeric_only=True))

inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms   Alley_ Pave   Alley_nan
0       3.0          True       False
1       2.0         False        True
2       4.0         False        True
3       3.0         False        True


2.2.3 转换为张量格式

In [26]:
import torch
x = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
x , y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

### 练习

创建包含更多行和列的原始数据集。

删除缺失值最多的列。

将预处理后的数据集转换为张量格式。

In [50]:
# 用html展示数据的模块
from IPython.display import display, HTML
import torch
import pandas as pd
# 创建文件路径
file_path = os.path.join('..', 'data', '.csv')

# 手动写入数据到文件
with open(file_path, 'w') as f:
    # 写入表头
    f.write('A,B,C,D,E,F\n')
    # 写入数据行
    f.write('Na,93.0,Na,,92.0,61.0\n')   # 包含 Na 和字符串
    f.write('21.0,83.0,87.0,75.0,75.0,Na\n')
    f.write('89.0,Na,42.0,91.0,25.0,63.0\n')  # 第二列是 Na
    f.write('60.0,21.0,37.0,89.0,Na,91.0\n')  # 第五列是 Na
    f.write('59.0,15.0,44.0,89.0,13.0,Na\n')  # 第六列是 Na
    f.write('Na,37.0,Na,78.0,26.0,29.0\n')  # 第一列是字符串
    f.write('Na,62.0,48.0,95.0,38.0,66.0\n')  # 第一列是 Na
    f.write('18.0,19.0,80.0,,Na,11.0\n')      # 多个 Na
    f.write('41.0,93.0,Na,14.0,60.0,61.0\n')
    f.write('Na,96.0,12.0,73.0,19.0,94.0\n')  # 第一列是 Na

# 读取数据
da = pd.read_csv(file_path,na_values=['Na'])
# 显示数据
#display(HTML(da.to_html()))

# 统计每一列缺失值
na_num = da.isna().sum()
print(na_num)
# 找出缺失值最多的列
max_miss_col = na_num.idxmax()
# 删除缺失值最多的列
da = da.drop(max_miss_col, axis = 1)
#display(HTML(da.to_html()))

# 用均值填充缺失值
da = da.fillna(da.mean(numeric_only=True))
# 转换为张量
a = torch.tensor(da.to_numpy(dtype=float))
a



A    4
B    1
C    3
D    2
E    2
F    2
dtype: int64


tensor([[93.0000, 50.0000, 75.5000, 92.0000, 61.0000],
        [83.0000, 87.0000, 75.0000, 75.0000, 59.5000],
        [57.6667, 42.0000, 91.0000, 25.0000, 63.0000],
        [21.0000, 37.0000, 89.0000, 43.5000, 91.0000],
        [15.0000, 44.0000, 89.0000, 13.0000, 59.5000],
        [37.0000, 50.0000, 78.0000, 26.0000, 29.0000],
        [62.0000, 48.0000, 95.0000, 38.0000, 66.0000],
        [19.0000, 80.0000, 75.5000, 43.5000, 11.0000],
        [93.0000, 50.0000, 14.0000, 60.0000, 61.0000],
        [96.0000, 12.0000, 73.0000, 19.0000, 94.0000]], dtype=torch.float64)