2.3.1 标量
标量没有维度，单独的一个数值

In [5]:
import  torch
x = torch.tensor(1.)
y = torch.tensor(3.1)
x , y, x+y, x*y, x/y  ,x**y

(tensor(1.),
 tensor(3.1000),
 tensor(4.1000),
 tensor(3.1000),
 tensor(0.3226),
 tensor(1.))

2.3.2 向量
向量是一维数组，有方向，有大小，有维度

In [6]:
z = torch.arange(12)
z   # 可以看到  数据 有 [] ，不是标量                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2.3.3 矩阵
矩阵是二维数组，有行有列，有维度

In [7]:
a = torch.arange(12).reshape(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

2.3.4 张量

In [17]:
a = torch.arange(24).reshape(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

2.3.5 张量算法的基本操作

In [25]:
b = a.clone()  # 深拷贝,重新分配内存,
#b = a  #浅拷贝，共享内存
print(id(a)==id(b))
a, a+b

False


(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [9]:
# 标量和张量的运算
l = 2
l *a , l + a, l - a, l / a

(tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]]),
 tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]),
 tensor([[ 2,  1,  0, -1],
         [-2, -3, -4, -5],
         [-6, -7, -8, -9]]),
 tensor([[   inf, 2.0000, 1.0000, 0.6667],
         [0.5000, 0.4000, 0.3333, 0.2857],
         [0.2500, 0.2222, 0.2000, 0.1818]]))

2.3.6 降维

降维求和
非降维求和

In [37]:
# 直接对一个维度求和会直接让这个维度消失
a = torch.arange(24).reshape(2,3,4)
print(a)
a.sum(axis=1)
# a.sum(axis=(0,1))
a.shape,  a.sum(axis=1).shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


(torch.Size([2, 3, 4]), torch.Size([2, 4]))

In [39]:
# 避免维度消失，可以使用keepdim=True
b = a.sum(axis= 1, keepdim=True)
a.shape, b.shape

(torch.Size([2, 3, 4]), torch.Size([2, 1, 4]))

In [40]:
# 通过广播机制，可以让两个不同维度的张量进行运算
a / b

tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]],

        [[0.2500, 0.2549, 0.2593, 0.2632],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4118, 0.4074, 0.4035]]])

In [50]:
# 累加,按照维度计算前缀和
a.cumsum(axis=1)


tensor([[[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21]],

        [[12, 13, 14, 15],
         [28, 30, 32, 34],
         [48, 51, 54, 57]]])

2.3.7 点积
- 哈达玛积 - 两个矩阵的对应元素相乘

In [52]:
a = torch.arange(12).reshape(3,4)
b = torch.arange(12).reshape(3,4)

a*b

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]])

In [55]:
# dot 乘法
c = torch.sum(a*b)
c

tensor(506)

2.3.8 矩阵 向量 乘法
2.3.9 矩阵 矩阵乘法
2.3.10 范数
L1范数:  张量的绝对值之和
L2范数：张量的模长

In [61]:
x = torch.tensor([3. , 4.])

# L1范数
l1 = torch.abs(x).sum()
# L2范数
l2 = torch.norm(x)
l1, l2

(tensor(7.), tensor(5.))

In [62]:
# 矩阵的Fronbenius范数-矩阵元素的平方和的平方根
torch.norm(torch.ones(4,9))

tensor(6.)