In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [87]:
def trans_conv(X, K):
    h, w = K.shape
    Y = torch.zeros(X.shape[0] + h - 1,X.shape[1] + w - 1)
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            Y[i:i+h, j:j+w] += K * X[i, j]
    return Y

In [88]:
X = torch.tensor([[0., 1.], [2., 3. ]])
K = torch.tensor([[0., 1.], [2., 3. ]])
K.shape

torch.Size([2, 2])

In [89]:
X, K = X.reshape(1, 1, 2, 2), K.reshape(1, 1, 2, 2)
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, bias =False)

tconv.weight.data = K 
tconv(X)

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)

In [90]:
tconv = nn.ConvTranspose2d(1, 1, kernel_size=2, padding=1, bias=False)

tconv.weight.data = K
tconv(X)

tensor([[[[4.]]]], grad_fn=<ConvolutionBackward0>)

In [91]:
tconv = nn.ConvTranspose2d(1, 1, kernel_size=3, stride=2, bias=False)
tconv.weight.data = K
tconv(X)

tensor([[[[0., 0., 0., 1.],
          [0., 0., 2., 3.],
          [0., 2., 0., 3.],
          [4., 6., 6., 9.]]]], grad_fn=<ConvolutionBackward0>)

In [92]:
X = torch.rand((1, 10, 16, 16))
conv = nn.Conv2d(10 ,20, kernel_size=5, padding=2, stride=3)
tconv = nn.ConvTranspose2d(20, 10 , kernel_size=5, padding=2,stride=3)

tconv(conv(X)).shape == X.shape

True

In [93]:
X = torch.arange(9.0).reshape(3, 3)
K = torch.tensor([[1., 2.], [3., 4.]])

Y = d2l.corr2d(X, K)
Y

tensor([[27., 37.],
        [57., 67.]])

In [94]:
def kernel2matrix(K):
    k, w = torch.zeros(5), torch.zeros(4, 9)
    k[:2], k[3:5] = K[0, :], K[1, :]
    for i in range(4):
        if i<2: 
            w[i,i:i+5] = k
        else:
            w[i,i+1 : i+6] = k
       

    return w

In [95]:
W = kernel2matrix(K)
W

tensor([[1., 2., 0., 3., 4., 0., 0., 0., 0.],
        [0., 1., 2., 0., 3., 4., 0., 0., 0.],
        [0., 0., 0., 1., 2., 0., 3., 4., 0.],
        [0., 0., 0., 0., 1., 2., 0., 3., 4.]])

In [96]:
Y == torch.matmul(W, X.reshape(-1)).reshape(2, 2)

tensor([[True, True],
        [True, True]])

In [97]:
Z = trans_conv(Y, K)
Z == torch.matmul(W.T, Y.reshape(-1)).reshape(3, 3)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])